# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bdafa9d3ad7789bc232c892cd48f8eb0fb062188e71107f671777327aaf469497f1abb87207f167119cce70d33fc2344e6f165f988e61ecafd0117a5c2b019d

test:
  secret_key_base: d9df6cb70dae8ee65e561ccb9de34173ba4157619c677075205e233bf9e28a4fd03a7c46754d0923479c7534f89f315a69f5d7f34a94d03ba3d43af4259ca7af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
